#!/bin/sh

CLASS="com.hazelcast.examples.SimpleMapClientTest"

CLASSPATH=$CLASSPATH:~/bin
CLASSPATH=$CLASSPATH:./target/classes
CLASSPATH=$CLASSPATH:../hazelcast/hazelcast/target/classes
CLASSPATH=$CLASSPATH:../hazelcast/hazelcast-client/target/classes
CLASSPATH=$CLASSPATH:~/.m2/repository/log4j/log4j/1.2.14/log4j-1.2.14.jar
CLASSPATH=$CLASSPATH:~/.m2/repository/org/hdrhistogram/HdrHistogram/1.0.9/HdrHistogram-1.0.9.jar

ARGS="$ARGS -ea"
ARGS="$ARGS -server"
ARGS="$ARGS -Xms2G -Xmx4G"
#ARGS="$ARGS -XX:+PrintGC"
ARGS="$ARGS -XX:MaxDirectMemorySize=24G"
#ARGS="$ARGS -XX:+UnlockCommercialFeatures -XX:+FlightRecorder"
#ARGS="$ARGS -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/work/tmp/"
ARGS="$ARGS -Dhazelcast.logging.type=log4j"
ARGS="$ARGS -Dhazelcast.version.check.enabled=false"
ARGS="$ARGS -Dhazelcast.multicast.group=224.3.5.7"
#ARGS="$ARGS -Dhazelcast.local.localAddress=127.0.0.1"


echo "CLASS: $CLASS"
echo "ARGS:  $ARGS"
echo "CLASSPATH: $CLASSPATH"

java $ARGS -cp $CLASSPATH $CLASS $@

